@baseUrl=http://localhost:3001/api

### GET api/contact
GET {{baseUrl}}/contact/

### GET api/contact/:mail
GET {{baseUrl}}/contact/example@example.com

### POST api/contact/submit
POST {{baseUrl}}/contact/submit
Content-Type: application/json

{
  "gender": "FEMALE",
  "firstName": "Lucy",
  "lastName": "MOTTOLA",
  "email": "example@example.com",
  "phone": "+33612121212",
  "message": "Bonjour, C'est un troisième message message.",
  "topic": "VISIT",
  "availabilities": [
    {
      "day": "MONDAY",
      "hour": 10,
      "minute": 30
    }
  ]
}